name: $(Build.DefinitionName)-$(date:yyyyMMdd)$(rev:.r)
trigger:
  branches:
    include:
    - 'development'
    - 'master'
    - 'feature/*'
    - 'hotfix/*'

jobs:
- job: Hosted
  pool:
    vmImage: 'Ubuntu-16.04'
    demands: npm

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install
      ng build --prod --output-path '$(Build.ArtifactStagingDirectory)/Web'
    workingDirectory: Web
    displayName: 'npm install and build'
    
  - task: CopyFiles@2
    displayName: 'Copy ARM Templates'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/ARM Template'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/ARM Template'

  - task: CopyFiles@2
    displayName: 'Copy Scripts'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/Scripts'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Scripts'

  - task: PublishBuildArtifacts@1
    condition: always()
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'